name: sub workflow

on:
  workflow_call:
    inputs:
      something:
        required: true
        type: string


jobs:
  display-context:
    runs-on: ubuntu-latest
    steps:
      - name: print context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "::notice ::value of something: ${{ github.event.inputs.something }}"
          echo "$GITHUB_CONTEXT"
      - name: Get input context
        run: echo ${{ inputs.something }}
